import { getWorker } from "@/lib/data";
import type { ComposeState, ConfigChangeLogItem, CustomerConfigItem, ImportedPackage, WorkerTemplate } from "./types";

export const draftWorker = getWorker("cobol-modernization-worker")!;

export const draftWillList = [
  "Analyze COBOL source code",
  "Understand JCL execution flows",
  "Analyze copybooks",
  "Extract business rules",
  "Identify data dependencies",
  "Design the target Java architecture",
  "Generate the Java implementation",
  "Generate tests",
  "Validate behavioral equivalence",
  "Reconcile source and target outputs",
  "Generate evidence of completion",
];

export const draftWontList = [
  ...draftWorker.scope.outOfScope,
  "Perform irreversible infrastructure changes",
  "Access systems it does not require",
];

export const templates: WorkerTemplate[] = [
  {
    id: "modernization",
    name: "Modernization Worker",
    description: "Rebuilds legacy applications in a modern language while proving functional parity.",
    capabilityCount: 8,
    suggestedModels: "Sonnet 5 + independent Opus 5 verifier",
    suggestedSafety: "Act With Approval — no production access",
    suggestedDoDCount: 5,
    namePrefill: draftWorker.name,
    objectivePrefill: draftWorker.scope.primaryPurpose,
    inputBoundaryPrefill: draftWorker.scope.acceptedInputBoundary,
    businessContextPrefill: "Engineering Transformation — bounded legacy-to-modern migration.",
    willList: draftWillList,
    skills: draftWorker.skills.map((s) => s.name),
    tools: draftWorker.tools.map((t) => t.name),
  },
  {
    id: "claims",
    name: "Claims Processing Worker",
    description: "Triages and processes incoming claims against policy and coverage rules.",
    capabilityCount: 6,
    suggestedModels: "Sonnet 5 + independent verifier",
    suggestedSafety: "Act With Approval — high-value claims always reviewed",
    suggestedDoDCount: 4,
    namePrefill: "Claims Processing Worker",
    objectivePrefill: "Process incoming claims against policy and coverage rules, routing exceptions to a human adjuster.",
    inputBoundaryPrefill: "Submitted claim forms, policy documents and supporting evidence from approved intake channels only.",
    businessContextPrefill: "Claims Operations — first-pass triage and processing.",
    willList: ["Validate claim completeness", "Match claim to policy coverage", "Flag suspected fraud indicators", "Draft settlement recommendation"],
    skills: ["Claims Triage", "Policy Matching", "Fraud Signal Detection", "Settlement Drafting"],
    tools: ["Policy Admin System", "Claims Ledger", "Document Store"],
  },
  {
    id: "document-intelligence",
    name: "Document Intelligence Worker",
    description: "Extracts and structures data from incoming enterprise documents.",
    capabilityCount: 5,
    suggestedModels: "Sonnet 5 + fast fallback",
    suggestedSafety: "Act Within Limits — read-only document access",
    suggestedDoDCount: 3,
    namePrefill: "Document Intelligence Worker",
    objectivePrefill: "Extract and structure data from incoming enterprise documents into the target schema.",
    inputBoundaryPrefill: "Approved document intake queues — PDFs, scans and structured forms only.",
    businessContextPrefill: "Operations — document intake and structuring.",
    willList: ["Classify document type", "Extract structured fields", "Validate against schema", "Flag low-confidence extractions"],
    skills: ["Document Classification", "Field Extraction", "Schema Validation"],
    tools: ["Document Store", "OCR Service"],
  },
  {
    id: "fraud",
    name: "Fraud Investigation Worker",
    description: "Investigates flagged transactions and produces evidence-backed findings.",
    capabilityCount: 7,
    suggestedModels: "Opus 5 + independent verifier",
    suggestedSafety: "Act With Approval — customer data access always logged",
    suggestedDoDCount: 4,
    namePrefill: "Fraud Investigation Worker",
    objectivePrefill: "Investigate flagged transactions and produce an evidence-backed findings report.",
    inputBoundaryPrefill: "Flagged transaction records and account history from the fraud queue only.",
    businessContextPrefill: "Risk & Fraud — flagged transaction investigation.",
    willList: ["Cross-reference transaction history", "Score fraud likelihood", "Assemble evidence package", "Draft findings report"],
    skills: ["Transaction Analysis", "Fraud Scoring", "Evidence Assembly"],
    tools: ["Case Management System", "Transaction Ledger"],
  },
  {
    id: "customer-service",
    name: "Customer Service Worker",
    description: "Resolves common customer requests within approved policy boundaries.",
    capabilityCount: 5,
    suggestedModels: "Haiku 4.5 + Sonnet 5 fallback",
    suggestedSafety: "Act Within Limits — no account modification without approval",
    suggestedDoDCount: 3,
    namePrefill: "Customer Service Worker",
    objectivePrefill: "Resolve common customer service requests within approved policy boundaries.",
    inputBoundaryPrefill: "Customer support tickets and account data visible through the support console only.",
    businessContextPrefill: "Customer Success — first-line request resolution.",
    willList: ["Answer policy questions", "Update non-sensitive account fields", "Escalate complex requests"],
    skills: ["Policy Q&A", "Account Lookup", "Escalation Routing"],
    tools: ["Support Console"],
  },
  {
    id: "underwriting",
    name: "Underwriting Worker",
    description: "Scores applications against underwriting guidelines and flags exceptions.",
    capabilityCount: 6,
    suggestedModels: "Sonnet 5 + independent verifier",
    suggestedSafety: "Act With Approval — high-risk decisions always reviewed",
    suggestedDoDCount: 4,
    namePrefill: "Underwriting Worker",
    objectivePrefill: "Score incoming applications against underwriting guidelines and route exceptions to a human underwriter.",
    inputBoundaryPrefill: "Submitted applications and bureau data from approved underwriting feeds only.",
    businessContextPrefill: "Underwriting — automated risk scoring.",
    willList: ["Score application risk", "Check guideline compliance", "Flag conflicting guidance", "Draft decision rationale"],
    skills: ["Risk Scoring", "Guideline Matching", "Decision Rationale"],
    tools: ["Bureau Data Feed"],
  },
  {
    id: "custom",
    name: "Custom Worker",
    description: "Start from a blank Worker and configure every step yourself.",
    capabilityCount: 0,
    suggestedModels: "Not yet configured",
    suggestedSafety: "Not yet configured",
    suggestedDoDCount: 0,
    namePrefill: "New AI Worker",
    objectivePrefill: "",
    inputBoundaryPrefill: "",
    businessContextPrefill: "",
    willList: [],
    skills: [],
    tools: [],
  },
];

export const availablePackages: ImportedPackage[] = [
  {
    id: "pkg-modernization",
    name: "Application Modernization Package",
    team: "Platform Engineering",
    version: "2.1",
    agents: 4,
    skills: ["Legacy Code Comprehension", "Target Architecture Design", "Java Code Generation", "Independent Verification"],
    tools: ["Repository Access", "Code Analysis Tool", "Test Environment"],
    apis: 3,
    lastUpdated: "2026-08-14",
    compatibility: "Compatible",
  },
  {
    id: "pkg-fraud",
    name: "Fraud Detection Package",
    team: "Risk Engineering",
    version: "1.4",
    agents: 3,
    skills: ["Transaction Analysis", "Fraud Scoring"],
    tools: ["Case Management System"],
    apis: 2,
    lastUpdated: "2026-07-30",
    compatibility: "Needs Review",
  },
  {
    id: "pkg-document",
    name: "Document Intelligence Package",
    team: "Data Platform",
    version: "3.0",
    agents: 2,
    skills: ["Document Classification", "Field Extraction"],
    tools: ["Document Store"],
    apis: 1,
    lastUpdated: "2026-08-22",
    compatibility: "Compatible",
  },
  {
    id: "pkg-claims",
    name: "Claims Automation Package",
    team: "Claims Operations",
    version: "1.9",
    agents: 5,
    skills: ["Claims Triage", "Policy Matching", "Settlement Drafting"],
    tools: ["Policy Admin System", "Claims Ledger"],
    apis: 4,
    lastUpdated: "2026-08-01",
    compatibility: "Compatible",
  },
  {
    id: "pkg-underwriting",
    name: "Underwriting Package",
    team: "Underwriting Engineering",
    version: "2.3",
    agents: 3,
    skills: ["Risk Scoring", "Guideline Matching"],
    tools: ["Bureau Data Feed"],
    apis: 2,
    lastUpdated: "2026-06-18",
    compatibility: "Compatible",
  },
];

export const customerConfigCatalog: { label: string; control: CustomerConfigItem["control"]; requiresApproval: boolean }[] = [
  { label: "Business rules & thresholds", control: "view", requiresApproval: false },
  { label: "Data sources & connections", control: "customer", requiresApproval: false },
  { label: "Model selection", control: "customer", requiresApproval: false },
  { label: "Monthly budget", control: "customer", requiresApproval: true },
  { label: "Automation limits", control: "customer", requiresApproval: false },
  { label: "Notifications & alerts", control: "customer", requiresApproval: false },
  { label: "Safety rules", control: "view", requiresApproval: false },
  { label: "Core agents & capabilities", control: "platform", requiresApproval: false },
];

export const changeLog: ConfigChangeLogItem[] = [
  { id: "cl-1", setting: "Automation Limit", from: "50", to: "75", changedBy: "Customer Admin — ABC Bank", status: "Pending Review", timestamp: "2026-09-01T14:20:00Z" },
  { id: "cl-2", setting: "Monthly Budget", from: "$4,000", to: "$4,500", changedBy: "Customer Admin — ABC Bank", status: "Approved", timestamp: "2026-08-27T09:05:00Z" },
];

function customerConfigDefaults(): CustomerConfigItem[] {
  return customerConfigCatalog.map((i, n) => ({ id: `cfg-${n}`, label: i.label, control: i.control, requiresApproval: i.requiresApproval }));
}

export function createComposeDefaults(templateId: string = "modernization"): ComposeState {
  const w = draftWorker;
  const template = templates.find((t) => t.id === templateId) ?? templates[0];
  return {
    templateId,
    name: template.namePrefill,
    owner: w.owner,
    businessContext: template.businessContextPrefill,
    objective: template.objectivePrefill,
    inputBoundary: template.inputBoundaryPrefill,
    willList: [...template.willList],
    wontList: [...draftWontList],
    capabilitiesMode: "build",
    skills: [...template.skills],
    tools: [...template.tools],
    importedPackage: null,
    operatingMode: w.operatingMode,
    alwaysRequireApproval: [...w.governance.alwaysRequireApproval],
    modelConfig: { ...w.modelConfig },
    deployment: { ...w.deployment },
    dodSections: w.definitionOfDone.sections.map((s) => ({
      id: s.id,
      title: s.title,
      requirements: s.requirements.map((r) => ({ ...r })),
    })),
    perTaskLimit: w.governance.budget.perTaskLimit,
    monthlyBudget: w.governance.budget.monthly,
    customerConfig: customerConfigDefaults(),
    syncMethod: "webhook",
  };
}

export const provisioningSteps = [
  "Creating Worker Identity",
  "Registering Worker Role",
  "Provisioning Agent Team",
  "Assigning Skills",
  "Applying Governance Policies",
  "Configuring Tool Access",
  "Connecting Knowledge Sources",
  "Registering Definition of Done",
  "Configuring Evaluation Baseline",
  "Activating Monitoring",
];
