import type { Knowledge, LearningEvent, SentinelReview, V2Worker } from "./types";

const HOUR = 3_600_000;
/** Timestamps are relative to load time so the activity feed always reads as recent. */
export const ago = (hours: number) => new Date(Date.now() - hours * HOUR).toISOString();

export const capabilityLadder = [
  "Code Conversion",
  "Code Conversion + Unit Testing",
  "Code Conversion + Traceability",
];

const INTEGRATION = "Integration Modernization Workers";

// ── Workers (ids match the Registry cards in registry-data.ts) ─────────────
export const initialWorkers: V2Worker[] = [
  {
    id: "wr-1",
    name: "Integration modernization · Payments",
    purpose: "Converts TIBCO services to Spring Boot",
    context: "Converts Integration Service to Target Code",
    contextTag: "Service conversion",
    status: "draft",
    revision: 11,
    maturityReasons: [],
    learningEnabled: true,
    assignedKnowledgeIds: ["a1", "a2", "a3", "a4", "a5", "a6", "a7", "a8", "a9"],
    evolution: {
      enabled: false,
      autoEvolve: false,
      currentCapability: "Code Conversion",
      availablePaths: capabilityLadder.slice(1),
      history: [],
    },
  },
  {
    id: "wr-2",
    name: "Integration modernization · Insurance claims",
    purpose: "Converts TIBCO services to Spring Boot for claims platforms",
    context: "Converts Integration Service to Target Code",
    contextTag: "Service conversion",
    status: "active",
    revision: 11,
    maturity: "platinum",
    maturityReasons: [
      "Repeated useful learning",
      "Learning survives validation",
      "Knowledge reused successfully",
      "Stable governance history",
    ],
    learningEnabled: true,
    assignedKnowledgeIds: ["a1", "a2", "a3", "a4", "a5", "a6", "a7", "a8", "a9"],
    evolution: {
      enabled: true,
      autoEvolve: true,
      currentCapability: "Code Conversion + Unit Testing",
      availablePaths: [capabilityLadder[2]],
      history: [
        {
          id: "ev-2a",
          from: "Code Conversion",
          to: "Code Conversion + Unit Testing",
          at: ago(27),
          reasons: ["Learning accumulated", "Validation completed", "Platform Sentinel approved"],
        },
      ],
    },
  },
  {
    id: "wr-3",
    name: "Integration modernization · Commercial lending",
    purpose: "Converts TIBCO services to Spring Boot with a traceability report",
    context: "Converts Integration Service to Traced Target Code",
    contextTag: "Service conversion",
    status: "active",
    revision: 11,
    maturity: "silver",
    maturityReasons: ["Started learning from its own work", "Some learning still under review"],
    learningEnabled: true,
    assignedKnowledgeIds: ["a1", "a2", "a3", "a4", "a5", "a6", "a7", "a8", "a9"],
    evolution: {
      enabled: true,
      autoEvolve: false,
      currentCapability: "Code Conversion + Traceability",
      availablePaths: [],
      history: [
        {
          id: "ev-3a",
          from: "Code Conversion",
          to: "Code Conversion + Traceability",
          at: ago(24 * 12),
          reasons: ["Required knowledge available", "Platform Sentinel approved"],
        },
      ],
    },
  },
  {
    id: "wr-4",
    name: "Integration modernization · Payments (with unit tests)",
    purpose: "Converts TIBCO services to Spring Boot and writes unit tests",
    context: "Converts Integration Service to Unit Tested Target Code",
    contextTag: "Service conversion",
    status: "active",
    revision: 11,
    maturity: "gold",
    maturityReasons: [
      "Repeated useful learning",
      "Learning survives validation",
      "Stable governance history",
    ],
    learningEnabled: true,
    assignedKnowledgeIds: ["a1", "a2", "a3", "a4", "a5", "a6", "a7", "a8", "a9", "a10"],
    evolution: {
      enabled: true,
      autoEvolve: true,
      currentCapability: "Code Conversion + Unit Testing",
      availablePaths: [capabilityLadder[2]],
      history: [
        {
          id: "ev-4a",
          from: "Code Conversion",
          to: "Code Conversion + Unit Testing",
          at: ago(24 * 9),
          reasons: ["Learning accumulated", "Required knowledge available", "Validation completed", "Platform Sentinel approved"],
        },
      ],
    },
  },
];

const assigned = (id: string, title: string, kind: Knowledge["kind"], summary: string, workers = ["wr-1", "wr-2", "wr-3", "wr-4"]): Knowledge => ({
  id,
  title,
  summary,
  scope: "assigned",
  kind,
  status: "active",
  usedByWorkerIds: workers,
  availableTo: [],
  history: [{ id: `${id}-h1`, label: "Assigned during Compose", at: ago(24 * 20) }],
});

// ── Knowledge ──────────────────────────────────────────────────────────────
export const initialKnowledge: Knowledge[] = [
  // Assigned — given to the Worker in Compose
  assigned("a1", "TIBCO → Spring Boot conversion", "skill", "Converts TIBCO BusinessWorks services into Spring Boot service classes while preserving business logic."),
  assigned("a2", "XML transformation", "skill", "Maps XML and XSD structures to typed Java models and back."),
  assigned("a3", "Service orchestration", "skill", "Rebuilds multi-step service flows as orchestrated Spring Boot services."),
  assigned("a4", "Java Spring Boot service class conversion", "skill", "Generates Java 21+ Spring Boot service classes from the source integration."),
  assigned("a5", "Engineering standards", "company", "House standards for structure, naming, testing and observability."),
  assigned("a6", "Approved architecture patterns", "company", "The integration and service patterns the organisation has approved."),
  assigned("a7", "Data handling rules", "rule", "How card data, account identifiers and customer data may be handled."),
  assigned("a8", "Security policies", "safety", "Security policies every generated service must respect."),
  assigned("a9", "Compliance guardrails", "safety", "Regulatory guardrails that bound what a Worker may produce."),
  assigned("a10", "Unit test authoring standards", "skill", "How unit tests are written, named and structured for converted services.", ["wr-4"]),

  // Gained — learned by a Worker
  {
    id: "g1",
    title: "JMS acknowledgement pattern",
    summary: "Client acknowledgement is safest when the listener acknowledges only after the downstream call succeeds.",
    scope: "gained",
    kind: "pattern",
    status: "active",
    usedByWorkerIds: ["wr-4"],
    sourceWorkerId: "wr-4",
    availableTo: ["This Worker"],
    validation: ["Reviewed by Worker Sentinel", "Kept with this Worker"],
    evidence: [
      { workerId: "wr-4", result: "ok" },
      { workerId: "wr-2", result: "ok" },
      { workerId: "wr-3", result: "warn" },
    ],
    history: [
      { id: "g1-h1", label: "Learned", detail: "A recurring pattern was seen across several runs.", at: ago(24 * 6) },
      { id: "g1-h2", label: "Reviewed", detail: "Worker Sentinel validated the learning.", at: ago(24 * 5) },
      { id: "g1-h3", label: "Kept by the Worker", at: ago(24 * 5) },
      { id: "g1-h4", label: "Kept with this Worker", detail: "Platform Sentinel decided not to share it yet.", at: ago(19) },
    ],
  },
  {
    id: "g2",
    title: "SOAP fault mapping",
    summary: "SOAP faults map cleanly to typed exceptions with a stable error-code table.",
    scope: "gained",
    kind: "pattern",
    status: "active",
    usedByWorkerIds: ["wr-2"],
    sourceWorkerId: "wr-2",
    availableTo: ["This Worker"],
    validation: ["Reviewed by Worker Sentinel"],
    evidence: [
      { workerId: "wr-2", result: "ok" },
      { workerId: "wr-4", result: "ok" },
    ],
    history: [
      { id: "g2-h1", label: "Learned", at: ago(24 * 8) },
      { id: "g2-h2", label: "Reviewed", detail: "Worker Sentinel validated the learning.", at: ago(24 * 7) },
      { id: "g2-h3", label: "Kept by the Worker", at: ago(24 * 7) },
    ],
  },
  {
    id: "g3",
    title: "Queue naming convention",
    summary: "Target queue names follow the environment-prefixed convention used by the platform team.",
    scope: "gained",
    kind: "pattern",
    status: "active",
    usedByWorkerIds: ["wr-4"],
    sourceWorkerId: "wr-4",
    availableTo: ["This Worker"],
    validation: ["Reviewed by Worker Sentinel", "Shared with the platform"],
    sharedAsId: "p10",
    evidence: [
      { workerId: "wr-4", result: "ok" },
      { workerId: "wr-2", result: "ok" },
    ],
    history: [
      { id: "g3-h1", label: "Learned", at: ago(24 * 4) },
      { id: "g3-h2", label: "Reviewed", at: ago(24 * 3) },
      { id: "g3-h3", label: "Kept by the Worker", at: ago(24 * 3) },
      { id: "g3-h4", label: "Shared with platform", detail: "Platform Sentinel decided on its own.", at: ago(26) },
    ],
  },
  {
    id: "g4",
    title: "Retry back-off defaults",
    summary: "Retries should back off exponentially and stop after a fixed ceiling.",
    scope: "gained",
    kind: "pattern",
    status: "under-review",
    usedByWorkerIds: ["wr-3"],
    sourceWorkerId: "wr-3",
    availableTo: ["This Worker"],
    validation: ["Worker Sentinel is reviewing this learning"],
    evidence: [
      { workerId: "wr-3", result: "ok" },
      { workerId: "wr-2", result: "warn" },
    ],
    history: [
      { id: "g4-h1", label: "Learned", detail: "A recurring pattern was detected.", at: ago(5) },
      { id: "g4-h2", label: "Under review", detail: "Waiting for Worker Sentinel.", at: ago(4) },
    ],
  },
  {
    id: "g5",
    title: "Unit test fixture setup",
    summary: "Shared fixtures for message payloads keep converted services' tests short and stable.",
    scope: "gained",
    kind: "pattern",
    status: "active",
    usedByWorkerIds: ["wr-4"],
    sourceWorkerId: "wr-4",
    availableTo: ["This Worker"],
    validation: ["Reviewed by Worker Sentinel"],
    evidence: [{ workerId: "wr-4", result: "ok" }],
    history: [
      { id: "g5-h1", label: "Learned", at: ago(24 * 2) },
      { id: "g5-h2", label: "Reviewed", at: ago(24 * 1.5) },
      { id: "g5-h3", label: "Kept by the Worker", at: ago(24 * 1.5) },
    ],
  },

  // Platform — approved for reuse
  {
    id: "p1",
    title: "TIBCO migration pattern",
    summary: "Standard mapping from TIBCO process activities to Spring Boot components.",
    scope: "platform",
    kind: "pattern",
    status: "revoked",
    usedByWorkerIds: [],
    sourceWorkerId: "wr-2",
    availableTo: [INTEGRATION],
    validation: ["Reviewed by Worker Sentinel", "Approved for platform use"],
    reason: "Failed validation",
    reasonContext: "Failed validation under the current runtime.",
    replacementKnowledgeId: "p2",
    history: [
      { id: "p1-h1", label: "Learned", at: ago(24 * 40) },
      { id: "p1-h2", label: "Validated", at: ago(24 * 38) },
      { id: "p1-h3", label: "Shared", detail: "Approved by Platform Sentinel.", at: ago(24 * 36) },
      { id: "p1-h4", label: "Used by Workers", at: ago(24 * 30) },
      { id: "p1-h5", label: "Contradictory evidence detected", tone: "warn", at: ago(24 * 6) },
      { id: "p1-h6", label: "Revoked", detail: "Failed validation under the current runtime.", tone: "bad", at: ago(24 * 5) },
      { id: "p1-h7", label: "Replaced", detail: "Superseded by TIBCO migration pattern v2.", at: ago(24 * 5) },
    ],
  },
  {
    id: "p2",
    title: "TIBCO migration pattern v2",
    summary: "Updated mapping that accounts for the current runtime's transaction handling.",
    scope: "platform",
    kind: "pattern",
    status: "active",
    usedByWorkerIds: ["wr-2", "wr-3", "wr-4"],
    sourceWorkerId: "wr-4",
    availableTo: [INTEGRATION],
    notRecommendedFor: ["Payments Workers", "Claims Workers"],
    validation: ["Reviewed by Worker Sentinel", "Approved for platform use"],
    derivedFromId: "g6",
    history: [
      { id: "p2-h1", label: "Learned", at: ago(24 * 9) },
      { id: "p2-h2", label: "Validated", at: ago(24 * 8) },
      { id: "p2-h3", label: "Shared", detail: "Approved by Platform Sentinel.", at: ago(24 * 5) },
      { id: "p2-h4", label: "Used by Workers", at: ago(24 * 4) },
    ],
  },
  {
    id: "p3",
    title: "Message ordering pattern",
    summary: "Preserve message ordering per business key by partitioning listeners.",
    scope: "platform",
    kind: "pattern",
    status: "active",
    usedByWorkerIds: ["wr-2", "wr-3"],
    sourceWorkerId: "wr-2",
    availableTo: [INTEGRATION],
    validation: ["Reviewed by Worker Sentinel", "Approved for platform use"],
    health: "contradictory",
    healthNote: "A recent run produced evidence that disagrees with this pattern.",
    history: [
      { id: "p3-h1", label: "Learned", at: ago(24 * 22) },
      { id: "p3-h2", label: "Validated", at: ago(24 * 20) },
      { id: "p3-h3", label: "Shared", at: ago(24 * 18) },
      { id: "p3-h4", label: "Used by Workers", at: ago(24 * 15) },
      { id: "p3-h5", label: "Contradictory evidence detected", tone: "warn", at: ago(30) },
    ],
  },
  {
    id: "p4",
    title: "JMS migration pattern",
    summary: "Convert JMS topic subscribers to point-to-point listeners with explicit acknowledgement.",
    scope: "platform",
    kind: "pattern",
    status: "active",
    usedByWorkerIds: ["wr-2", "wr-4"],
    sourceWorkerId: "wr-4",
    availableTo: [INTEGRATION],
    validation: ["Reviewed by Worker Sentinel", "Approved for platform use"],
    health: "outdated",
    healthNote: "The runtime it was validated against has since changed.",
    history: [
      { id: "p4-h1", label: "Learned", at: ago(24 * 60) },
      { id: "p4-h2", label: "Validated", at: ago(24 * 58) },
      { id: "p4-h3", label: "Shared", at: ago(24 * 55) },
      { id: "p4-h4", label: "Used by Workers", at: ago(24 * 50) },
    ],
  },
  {
    id: "p5",
    title: "Queue listener conversion (v1)",
    summary: "First-generation conversion of queue listeners.",
    scope: "platform",
    kind: "pattern",
    status: "replaced",
    usedByWorkerIds: [],
    sourceWorkerId: "wr-3",
    availableTo: [INTEGRATION],
    validation: ["Approved for platform use"],
    reason: "Replaced by newer knowledge",
    reasonContext: "Superseded by the v2 conversion.",
    replacementKnowledgeId: "p6",
    history: [
      { id: "p5-h1", label: "Learned", at: ago(24 * 70) },
      { id: "p5-h2", label: "Shared", at: ago(24 * 65) },
      { id: "p5-h3", label: "Replaced", detail: "Superseded by Queue listener conversion (v2).", at: ago(24 * 14) },
    ],
  },
  {
    id: "p6",
    title: "Queue listener conversion (v2)",
    summary: "Current conversion of queue listeners, including dead-letter handling.",
    scope: "platform",
    kind: "pattern",
    status: "active",
    usedByWorkerIds: ["wr-2", "wr-3", "wr-4"],
    sourceWorkerId: "wr-3",
    availableTo: [INTEGRATION],
    validation: ["Reviewed by Worker Sentinel", "Approved for platform use"],
    history: [
      { id: "p6-h1", label: "Learned", at: ago(24 * 20) },
      { id: "p6-h2", label: "Validated", at: ago(24 * 17) },
      { id: "p6-h3", label: "Shared", at: ago(24 * 14) },
      { id: "p6-h4", label: "Used by Workers", at: ago(24 * 12) },
    ],
  },
  {
    id: "p7",
    title: "Spring Boot exception handling",
    summary: "Central exception translation with consistent error payloads.",
    scope: "platform",
    kind: "pattern",
    status: "active",
    usedByWorkerIds: ["wr-2", "wr-3", "wr-4"],
    sourceWorkerId: "wr-2",
    availableTo: ["All Workers"],
    validation: ["Reviewed by Worker Sentinel", "Approved for platform use"],
    history: [
      { id: "p7-h1", label: "Learned", at: ago(24 * 45) },
      { id: "p7-h2", label: "Validated", at: ago(24 * 43) },
      { id: "p7-h3", label: "Shared", at: ago(24 * 40) },
      { id: "p7-h4", label: "Used by Workers", at: ago(24 * 35) },
    ],
  },
  {
    id: "p8",
    title: "Sanitised logging conventions",
    summary: "Never log message bodies that may carry customer data.",
    scope: "platform",
    kind: "pattern",
    status: "active",
    usedByWorkerIds: ["wr-2", "wr-3", "wr-4"],
    sourceWorkerId: "wr-3",
    availableTo: ["All Workers"],
    validation: ["Reviewed by Worker Sentinel", "Approved for platform use"],
    history: [
      { id: "p8-h1", label: "Learned", at: ago(24 * 33) },
      { id: "p8-h2", label: "Validated", at: ago(24 * 31) },
      { id: "p8-h3", label: "Shared", at: ago(24 * 28) },
    ],
  },
  {
    id: "p9",
    title: "Contract test scaffolding",
    summary: "A reusable scaffold for consumer-driven contract tests.",
    scope: "platform",
    kind: "pattern",
    status: "active",
    usedByWorkerIds: ["wr-4"],
    sourceWorkerId: "wr-4",
    availableTo: ["Integration Workers"],
    validation: ["Reviewed by Worker Sentinel", "Approved for platform use"],
    history: [
      { id: "p9-h1", label: "Learned", at: ago(24 * 26) },
      { id: "p9-h2", label: "Shared", at: ago(24 * 21) },
    ],
  },

  {
    id: "p10",
    title: "Queue naming convention",
    summary: "Target queue names follow the environment-prefixed convention used by the platform team.",
    scope: "platform",
    kind: "pattern",
    status: "active",
    usedByWorkerIds: ["wr-4"],
    sourceWorkerId: "wr-4",
    availableTo: ["Integration Workers"],
    validation: ["Reviewed by Worker Sentinel", "Approved for platform use"],
    derivedFromId: "g3",
    history: [
      { id: "p10-h1", label: "Learned", at: ago(24 * 4) },
      { id: "p10-h2", label: "Validated", at: ago(24 * 3) },
      { id: "p10-h3", label: "Shared", detail: "Platform Sentinel decided on its own.", at: ago(26) },
    ],
  },

  // A gained item that has already been shared; p2 points back to it.
  {
    id: "g6",
    title: "TIBCO transaction handling",
    summary: "Transaction boundaries in TIBCO flows should map to a single Spring transaction per message.",
    scope: "gained",
    kind: "pattern",
    status: "active",
    usedByWorkerIds: ["wr-4"],
    sourceWorkerId: "wr-4",
    availableTo: ["This Worker"],
    validation: ["Reviewed by Worker Sentinel", "Shared with the platform"],
    sharedAsId: "p2",
    evidence: [
      { workerId: "wr-4", result: "ok" },
      { workerId: "wr-2", result: "ok" },
    ],
    history: [
      { id: "g6-h1", label: "Learned", at: ago(24 * 9) },
      { id: "g6-h2", label: "Reviewed", at: ago(24 * 8) },
      { id: "g6-h3", label: "Shared with platform", at: ago(24 * 5) },
    ],
  },
];

// Workers keep the gained items they learned; derived from `sourceWorkerId`.
export function gainedFor(workerId: string, knowledge: Knowledge[]) {
  return knowledge.filter((k) => k.scope === "gained" && k.sourceWorkerId === workerId);
}

// ── Learning activity ──────────────────────────────────────────────────────
export const initialEvents: LearningEvent[] = [
  { id: "le-1", workerId: "wr-3", type: "pattern-identified", title: "New pattern identified", description: "A recurring retry pattern was detected across several runs.", timestamp: ago(5), knowledgeId: "g4" },
  { id: "le-2", workerId: "wr-3", type: "learning-reviewed", title: "Worker Sentinel is reviewing", description: "Retry back-off defaults are waiting for a decision.", timestamp: ago(4), knowledgeId: "g4" },
  { id: "le-3", workerId: "wr-4", type: "knowledge-gained", title: "Knowledge gained", description: "Unit test fixture setup was added to the Worker.", timestamp: ago(30), knowledgeId: "g5" },
  { id: "le-4", workerId: "wr-2", type: "pattern-identified", title: "New pattern identified", description: "Contradictory evidence was seen for the message ordering pattern.", timestamp: ago(30), knowledgeId: "p3" },
  { id: "le-5", workerId: "wr-2", type: "evolution-approved", title: "Evolution approved", description: "Platform Sentinel let the Worker evolve to Code Conversion + Unit Testing.", timestamp: ago(27) },
  { id: "le-12", workerId: "wr-4", type: "knowledge-shared", title: "Knowledge shared with platform", description: "Platform Sentinel shared Queue naming convention with Integration Workers.", timestamp: ago(26), knowledgeId: "p10" },
  { id: "le-13", workerId: "wr-4", type: "learning-reviewed", title: "Kept with the Worker", description: "Platform Sentinel kept JMS acknowledgement pattern with this Worker for now.", timestamp: ago(19), knowledgeId: "g1" },
  { id: "le-6", workerId: "wr-4", type: "knowledge-gained", title: "Knowledge gained", description: "Queue naming convention was added to the Worker.", timestamp: ago(24 * 3), knowledgeId: "g3" },
  { id: "le-7", workerId: "wr-2", type: "knowledge-revoked", title: "Knowledge revoked", description: "TIBCO migration pattern failed validation and was replaced by v2.", timestamp: ago(24 * 5), knowledgeId: "p1" },
  { id: "le-8", workerId: "wr-4", type: "knowledge-shared", title: "Knowledge shared with platform", description: "TIBCO migration pattern v2 is now trusted for Integration Modernization Workers.", timestamp: ago(24 * 5), knowledgeId: "p2" },
  { id: "le-9", workerId: "wr-4", type: "learning-rejected", title: "Learning rejected", description: "A one-off workaround was not kept.", timestamp: ago(24 * 6) },
  { id: "le-10", workerId: "wr-4", type: "evolution-approved", title: "Evolution approved", description: "The Worker can now convert code and write unit tests.", timestamp: ago(24 * 9) },
  { id: "le-11", workerId: "wr-3", type: "evolution-approved", title: "Evolution approved", description: "The Worker can now convert code with a traceability report.", timestamp: ago(24 * 12) },
];

// ── Sentinel ───────────────────────────────────────────────────────────────
export const initialReviews: SentinelReview[] = [
  {
    id: "r1",
    level: "platform",
    type: "knowledge-sharing",
    subjectId: "g1",
    status: "approved",
    automatic: true,
    decision: "Kept with the Worker",
    reasoning: "One of the three Workers that tried it saw mixed results, so it stays with this Worker for now.",
    suggestedScope: [INTEGRATION],
    createdAt: ago(20),
    decidedAt: ago(19),
  },
  {
    id: "r2",
    level: "worker",
    type: "learning",
    subjectId: "g4",
    status: "needs-review",
    createdAt: ago(4),
  },
  {
    id: "r3",
    level: "platform",
    type: "evolution",
    subjectId: "wr-2",
    status: "approved",
    automatic: true,
    decision: "Evolution approved",
    reasoning: "Repeated successful learning was detected and the relevant tests passed.",
    proposedCapability: "Code Conversion + Unit Testing",
    createdAt: ago(28),
    decidedAt: ago(27),
  },
  {
    id: "r4",
    level: "platform",
    type: "knowledge-sharing",
    subjectId: "g3",
    status: "approved",
    automatic: true,
    decision: "Shared with platform",
    reasoning: "Both Workers that tried it agreed, so it was shared with Integration Workers.",
    suggestedScope: ["Integration Workers"],
    createdAt: ago(27),
    decidedAt: ago(26),
  },
];
